on:
  push:
    branches:
    - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build maven app
      run: mvn -B package --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: Build
          path: ./*

  # Staging:
  #   runs-on: ubuntu-latest
  #   needs: Build
  #   steps:
  #     - name: Get artifact
  #       uses: actions/download-artifact@v3
  #     - name: DockerHub Login
  #       uses: docker/login-action@v3.0.0
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Build and push Docker images
  #       uses: docker/build-push-action@v5.1.0
  #       with:
  #         push: true
  #         tags: mrneedhelp/adv6keycloak-manager:latest

  Staging:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
      - name: DockerHub Login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build . -t mrneedhelp/adv6keycloak-manager:latest
      - name: Push image to registry
        run: docker push mrneedhelp/adv6keycloak-manager:latest

  Deploy:
    runs-on: [self-hosted, Windows, X64]
    needs: Staging
    steps:
      -  name: Pull image
         run: docker pull mrneedhelp/adv6keycloak-manager:latest
      -  name: Run image
         run: docker run -p 8081:8081 -d mrneedhelp/adv6keycloak-manager:latest
