on:
  push:
    branches:
    - main
#%
jobs:
  BuildApp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload JAR file
      uses: actions/upload-artifact@v2
      with:
        name: keycloak-jar
        path: target/keycloak-0.0.1-SNAPSHOT.jar # Replace with the correct path to your JAR

      
  BuildAndPushContainer:
    runs-on: ubuntu-latest
    needs: BuildApp
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: keycloak-jar
          path: target # Path to download the artifact

      # Your other steps for Docker login and image building...

      - name: DockerHub Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: mrneedhelp/adv6keycloak-manager:latest
          
  Deploy:
    runs-on: [self-hosted, Windows, X64]
    needs: BuildAndPushContainer
    steps:
      -  name: Deploy Local machine docker container
         run: docker run -p 8081:8081 -d mrneedhelp/adv6keycloak-manager:latest
