on:
  push:
    branches:
    - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build maven app
      run: mvn -B package --file pom.xml
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: Build
          path: ./

  SonarCloud:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    -  name: Get artifact
       uses: actions/download-artifact@v3
       with:
          name: Build
          Path: build
       
    -  name: Unzip artifact
       run: zip -r Build.zip build/

    -  name: Sonar scan
       uses: SonarSource/sonarcloud-github-action@49e6cd3b187936a73b8280d59ffd9da69df63ec9
       with:
         projectBaseDir: build/
         args: >
           -Dsonar.projectKey= ${{ secrets.SONAR_PROJECT_KEY }}
           -Dsonar.organization= ${{ secrets.SONAR_KEY }}
       env:
         GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       
        

  Staging:
    runs-on: ubuntu-latest
    needs: [SonarCloud]
    steps:
      - name: Get artifact
        uses: actions/download-artifact@v3
        with:
          name: Build
          Path: build
      - name: Unzip artifact
        run: zip -r Build.zip build/
      - name: DockerHub Login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Build Docker image
        run: docker build build/ -t mrneedhelp/adv6keycloak-manager:latest
      - name: Push image to registry
        run: docker push mrneedhelp/adv6keycloak-manager:latest

  Deploy:
    runs-on: [self-hosted, Windows, X64]
    needs: Staging
    steps:
      -  name: Pull image
         run: docker pull mrneedhelp/adv6keycloak-manager:latest
      -  name: Run image
         run: docker run -p 8081:8081 -d mrneedhelp/adv6keycloak-manager:latest
