name: Deploy to Localhost
#test
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, windows, x86]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: |
          docker run -p 8081:8081 mrneedhelp/adv6keycloak-manager:latest
