name: Deploy to Localhost
#test
on:
  push:
    branches:
      - main
#1
jobs:
  deploy:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: |
          docker run -p 8081:8081 -d mrneedhelp/adv6keycloak-manager:latest
