on:
  push:
    branches:
    - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Build postgress
      run: docker run postgres -e POSTGRES_USER="mysecretuser" -e POSTGRES_PASSWORD="mysecretpassword" -p 5431:5432
