on:
  push:
    branches:
    - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Build PostgreSQL
      run: docker run -d -e POSTGRES_USER=mysecretuser -e POSTGRES_PASSWORD=mysecretpassword -p 5431:5432 postgres
    - name: check if docker is running postgres
      run: docker ps
